"""add listening_events and skip_events tables

Revision ID: ac6a72e3084c
Revises: 61b8f901a394
Create Date: 2026-08-05 19:16:14.339232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6a72e3084c'
down_revision: Union[str, Sequence[str], None] = '61b8f901a394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', 'played_at', name='uq_listening_event')
    )
    op.create_index(op.f('ix_listening_events_user_id'), 'listening_events', ['user_id'], unique=False)
    op.create_table('skip_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('played_ms', sa.Integer(), nullable=False),
    sa.Column('track_duration_ms', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skip_events_user_id'), 'skip_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skip_events_user_id'), table_name='skip_events')
    op.drop_table('skip_events')
    op.drop_index(op.f('ix_listening_events_user_id'), table_name='listening_events')
    op.drop_table('listening_events')
    # ### end Alembic commands ###
